language: "perl"
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"

before_install:
  - sudo apt-get update -q
  - sudo apt-get install -y libdatetime-locale-perl

install:
  - true

script: "unit-test/test1.sh"

# branches:
#   only:
#     - master

# notifications:
#   recipients:
#     - 
#   email:
#     on_success: change
#     on_failure: always

# env:
